# Generated by Django 2.2.1 on 2019-07-14 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('escuela', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('rol', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
                ('estante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tutor', models.CharField(max_length=50)),
                ('jurado1', models.CharField(max_length=50)),
                ('jurado2', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('resumen', models.CharField(max_length=200)),
                ('calificacion', models.FloatField()),
                ('estatus', models.CharField(max_length=50)),
                ('escuela', models.CharField(max_length=50)),
                ('palabra_clave', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('autor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_1', to='buscador.Autor')),
                ('autor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_2', to='buscador.Autor')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.Persona')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.Ubicacion')),
            ],
        ),
    ]
